@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

Deployment_Node(gcp, "Google Cloud", "IaaS") {
    Deployment_Node(prod, "K8s Cluster", "Production")
    Deployment_Node(test, "K8s Cluster", "Production")
    Deployment_Node(dev, "K8s Cluster", "Production")
}

@enduml
