spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fettle.us.auth0.com/
---
spring:
  config:
    activate:
      on-profile: local
github:
  token: ${GH_TOKEN}
  user: ${GH_USER:fidil}