name: Release

on:
  pull_request:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Install dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --no-ci

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/